### ISSUE TITLE
Authorization Error

### ISSUE THREAD

**Issue by kosirm** [DmitrySharabin/mavo-gsheets#3] opened 2023-11-28 23:55 UTC
Hi, I'm trying to use your plugin, but I get a login error from google.

![Screenshot 2023-11-29 003257](https://github.com/DmitrySharabin/mavo-gsheets/assets/54502/31519079-3408-4c8d-8566-37fe48ae9a94)

If I click on error details I get this:

![Screenshot 2023-11-29 003408](https://github.com/DmitrySharabin/mavo-gsheets/assets/54502/e570166d-be9e-43a6-b014-59dd0a51ad34)

If I go to mavo auth address (redirect_uri) by myself, looks good:

![Screenshot 2023-11-29 003952](https://github.com/DmitrySharabin/mavo-gsheets/assets/54502/da847475-14c6-41cc-92c6-e0183ed17dd9)

Do you maybe know what could be the problem?

**Comment by DmitrySharabin** [comment] 2023-11-29 11:48
Hey @kosirm,

Thank you so much for reporting the issue. I'll try to re-submit my app for verification to Google ASAP. I will let you know when the issue is fixed. Sorry for the inconvenience.

**Comment by DmitrySharabin** [comment] 2023-12-11 13:58
@kosirm, the issue should be fixed now (you might need to clear the cache before testing the plugin — the new plugin version is 1.0.11). Please feel free to reopen it if it's not.

**Closed as completed by DmitrySharabin** 2023-12-11 13:58 UTC
Labels: priority: high
